services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - db
    env_file:
      - .env
    command: bun run --hot src/app.ts
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/bun.lockb
    ports:
      - "3000:3000"

volumes:
  db_data:
